### ISSUE TITLE
Blocks changing to dirt blocks

### ISSUE THREAD

**Issue by ca-schaefer** [minecraft-saar/spigot-plugin#15]
Conditions under which blocks tend to change into dirt blocks:
- blocks change a few seconds after another block is placed on them
- they change if they are above grass blocks but not above bedrock blocks
- affected materials: wool, sponge

**Comment by akoehn** [comment]
Is this still a problem with our current setup?

**Comment by ca-schaefer** [comment]
No, I only observed it in combination with grass blocks. In the current setup all former grass blocks are replaced with lime concrete blocks.
