### ISSUE TITLE
Update to Minecraft 15.2

### ISSUE THREAD

**Issue by akoehn** [minecraft-saar/spigot-plugin#18]
Should be a straight-forward change as the plugin interface has not changes afaik.

**Comment by akoehn** [comment]
Just tried it: everything works fine with the 15.2 server without any changes. We might want to update the libraries anyway; don't know what changed there.

**Comment by ca-schaefer** [comment]
Plugin updated in a779675ac1501cf4ef11fc5ec8c2efb6c6a5efba
